### ISSUE TITLE
Remover string de conexão

### ISSUE THREAD

**Issue by chmieleski** [JulianoRSousa/ApiPets#2]
Cara, eu acho melhor você criar um helper para montar a string de conexão e deixar os dados sensíveis em um .env

https://github.com/JulianoRSousa/ApiPets/blob/a4ae4f18ab7c8611c69b737927fb75efb0799cab/src/server.js#L11

**Comment by JulianoRSousa** [comment]
> Cara, eu acho melhor você criar um helper para montar a string de conexão e deixar os dados sensíveis em um .env
> 
> https://github.com/JulianoRSousa/ApiPets/blob/a4ae4f18ab7c8611c69b737927fb75efb0799cab/src/server.js#L11

Estou configurando isso ainda, tive alguns problemas com o .env mas era exatamente como iria fazer. Já o helper não havia pensado, mas vai facilitar bastante o entendimento. Obrigado

**Comment by JulianoRSousa** [comment]
> Cara, eu acho melhor você criar um helper para montar a string de conexão e deixar os dados sensíveis em um .env
> 
> https://github.com/JulianoRSousa/ApiPets/blob/a4ae4f18ab7c8611c69b737927fb75efb0799cab/src/server.js#L11

Estou configurando isso ainda, tive alguns problemas com o .env mas era exatamente como iria fazer. Já o helper não havia pensado, mas vai facilitar bastante o entendimento. Obrigado
